"""empty message

Revision ID: 0470e4fe8b69
Revises: 14dd711e4416
Create Date: 2021-06-21 12:50:41.438770

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0470e4fe8b69'
down_revision = '14dd711e4416'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'users_ibfk_2', 'users', type_='foreignkey')
    op.drop_constraint(u'users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'country_id')
    op.drop_column('users', 'status_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('country_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'users_ibfk_1', 'users', 'countries', ['country_id'], ['id'])
    op.create_foreign_key(u'users_ibfk_2', 'users', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###
