"""empty message

Revision ID: 06c020cdf7a5
Revises: 57464a78e26b
Create Date: 2021-06-17 10:04:30.806937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c020cdf7a5'
down_revision = '57464a78e26b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'status_id')
    # ### end Alembic commands ###
