"""empty message

Revision ID: 07ea67c5d13a
Revises: bb8d1119361c
Create Date: 2021-06-22 13:26:23.393981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '07ea67c5d13a'
down_revision = 'bb8d1119361c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'country_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'users', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.alter_column('users', 'country_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
