"""empty message

Revision ID: 14dd711e4416
Revises: 52502581acfd
Create Date: 2021-06-21 12:49:01.657067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '14dd711e4416'
down_revision = '52502581acfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'users_ibfk_3', 'users', type_='foreignkey')
    op.drop_column('users', 'contact_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('contact_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'users_ibfk_3', 'users', 'contacts', ['contact_id'], ['id'])
    # ### end Alembic commands ###
