"""empty message

Revision ID: 202336d75a8f
Revises: a0134054e126
Create Date: 2021-06-21 12:26:15.550265

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '202336d75a8f'
down_revision = 'a0134054e126'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'contacts_ibfk_2', 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'user_id')
    op.add_column('users', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'contacts', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'contact_id')
    op.add_column('contacts', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'contacts_ibfk_2', 'contacts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
