"""empty message

Revision ID: 25b91bf1e23e
Revises: 07ea67c5d13a
Create Date: 2021-06-22 14:00:54.543902

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '25b91bf1e23e'
down_revision = '07ea67c5d13a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'dependants_ibfk_1', 'dependants', type_='foreignkey')
    op.drop_column('dependants', 'user_id')
    op.drop_column('users', 'country_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('country_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('dependants', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'dependants_ibfk_1', 'dependants', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
