"""empty message

Revision ID: 52502581acfd
Revises: 202336d75a8f
Create Date: 2021-06-21 12:47:21.466649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '52502581acfd'
down_revision = '202336d75a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'dependants_ibfk_1', 'dependants', type_='foreignkey')
    op.drop_column('dependants', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependants', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(u'dependants_ibfk_1', 'dependants', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
