"""empty message

Revision ID: 57bec4408345
Revises: c84c056cffac
Create Date: 2021-06-20 17:00:37.836705

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '57bec4408345'
down_revision = 'c84c056cffac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('iso_alpha3', sa.String(length=5), nullable=True))
    op.create_unique_constraint(None, 'countries', ['iso_alpha3'])
    op.create_unique_constraint(None, 'countries', ['m49_code'])
    op.alter_column('dependants', 'relationship',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.add_column('status', sa.Column('name', sa.String(length=60), nullable=True))
    op.drop_index('status', table_name='status')
    op.create_unique_constraint(None, 'status', ['name'])
    op.drop_column('status', 'status')
    op.add_column('users', sa.Column('date_of_birth', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_of_birth')
    op.add_column('status', sa.Column('status', mysql.VARCHAR(length=60), nullable=True))
    op.drop_constraint(None, 'status', type_='unique')
    op.create_index('status', 'status', ['status'], unique=False)
    op.drop_column('status', 'name')
    op.alter_column('dependants', 'relationship',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(None, 'countries', type_='unique')
    op.drop_constraint(None, 'countries', type_='unique')
    op.drop_column('countries', 'iso_alpha3')
    # ### end Alembic commands ###
