"""empty message

Revision ID: 93b27739be67
Revises: b26206d41c5a
Create Date: 2021-06-17 09:53:02.032848

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '93b27739be67'
down_revision = 'b26206d41c5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='provinces')
    op.drop_table('provinces')
    op.add_column('users', sa.Column('country_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('create_date', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('update_date', sa.DateTime(), nullable=False))
    op.create_foreign_key(None, 'users', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'update_date')
    op.drop_column('users', 'create_date')
    op.drop_column('users', 'country_id')
    op.create_table('provinces',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('country_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], [u'countries.id'], name=u'provinces_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8mb4_0900_ai_ci',
    mysql_default_charset=u'utf8mb4',
    mysql_engine=u'InnoDB'
    )
    op.create_index('name', 'provinces', ['name'], unique=False)
    # ### end Alembic commands ###
