"""empty message

Revision ID: 9baa73194d61
Revises: ca052bb90759
Create Date: 2021-06-17 09:25:51.865849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9baa73194d61'
down_revision = 'ca052bb90759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'users_ibfk_3', 'users', type_='foreignkey')
    op.drop_constraint(u'users_ibfk_1', 'users', type_='foreignkey')
    op.drop_column('users', 'country_id')
    op.drop_column('users', 'status_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('country_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'users_ibfk_1', 'users', 'countries', ['country_id'], ['id'])
    op.create_foreign_key(u'users_ibfk_3', 'users', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###
