"""empty message

Revision ID: a0134054e126
Revises: 57bec4408345
Create Date: 2021-06-20 17:12:25.198241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0134054e126'
down_revision = '57bec4408345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dependants', 'date_of_birth',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.add_column('users', sa.Column('date_of_birth', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_of_birth')
    op.alter_column('dependants', 'date_of_birth',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
