"""empty message

Revision ID: b26206d41c5a
Revises: 9baa73194d61
Create Date: 2021-06-17 09:43:04.474707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b26206d41c5a'
down_revision = '9baa73194d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_gender', table_name='users')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birthdate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birthdate', mysql.DATETIME(), nullable=True))
    op.add_column('users', sa.Column('gender', mysql.VARCHAR(length=10), nullable=True))
    op.create_index('ix_users_gender', 'users', ['gender'], unique=False)
    # ### end Alembic commands ###
