"""empty message

Revision ID: bb8d1119361c
Revises: 0470e4fe8b69
Create Date: 2021-06-22 13:06:12.825661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb8d1119361c'
down_revision = '0470e4fe8b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dependants', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'dependants', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('country_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'countries', ['country_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'country_id')
    op.drop_constraint(None, 'dependants', type_='foreignkey')
    op.drop_column('dependants', 'user_id')
    # ### end Alembic commands ###
