"""empty message

Revision ID: ca052bb90759
Revises: e86c163f564b
Create Date: 2021-06-15 09:02:14.018973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca052bb90759'
down_revision = 'e86c163f564b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'users_ibfk_2', 'users', type_='foreignkey')
    op.drop_column('users', 'province_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('province_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'users_ibfk_2', 'users', 'provinces', ['province_id'], ['id'])
    # ### end Alembic commands ###
