"""Insecond migration.

Revision ID: d2054c30db58
Revises: e330824d4f2b
Create Date: 2021-06-13 17:12:56.102116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2054c30db58'
down_revision = 'e330824d4f2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provinces', 'country_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.add_column('users', sa.Column('birthdate', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birthdate')
    op.alter_column('provinces', 'country_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
