"""Insecond migration.

Revision ID: e86c163f564b
Revises: d2054c30db58
Create Date: 2021-06-13 17:18:47.029054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e86c163f564b'
down_revision = 'd2054c30db58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'status', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'status_id')
    # ### end Alembic commands ###
